### ISSUE TITLE
Addition of SM based Stocks

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/eod2#31]
Hello Benny,

It just a suggestion, you are filtering the EQ, BE and BZ. It does not have SME based stocks.
Can you include the same in the code.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Hi Saurabh,

The bhavcopy doesn't include SME stocks, they are released as a separate report (SME- Bhavcopy file). [See NSE series legend](https://www.nseindia.com/market-data/legend-of-series)

I'm not keen on adding any new data source to this repo. It would require maintaining additional data i.e corporate actions for all the years, bhavcopy reports etc. This is required to recreate the data if due to unforeseen errors the data is corrupted.

The feature itself is trivial to implement since a lot of the code is already in place. I can create a separate repo (just the code) if you strongly need it. But i will need time.

Currently i am working on improving and adding new features to `plot.py` and updating the wiki for all features recently added.

**Comment by cotton1234** [comment]
Thanks for the reply. 

Don't create new code just for this. Data is already coming in Bhav copy.

saurabhgarg@Saurabhs-MacBook-Pro 2023 % grep ',SM,' cm08AUG2023bhav.csv
INE0OB201016,AATMAJ,SM,46.85,48.6,46.5,48.6,48.6,46.85,44000,2067100.0,08-AUG-2023,19,
INE0MLA01012,AGARWALFT,SM,36.0,36.0,35.0,35.95,35.95,35.5,9000,320850.0,08-AUG-2023,3,
INE0LF301013,AGNI,SM,21.5,21.5,20.5,20.5,20.5,21.5,30000,629000.0,08-AUG-2023,6,
INE0O6N01012,AGUL,SM,50.0,50.0,48.5,48.5,48.5,52.0,4000,197000.0,08-AUG-2023,2,
INE0CAJ01017,AILIMITED,SM,32.75,33.2,32.75,33.2,33.2,34.45,24000,788700.0,08-AUG-2023,4,
INE635Y01015,AISL,SM,58.7,58.7,58.7,58.7,58.7,57.4,1200,70440.0,08-AUG-2023,1,

![image](https://github.com/BennyThadikaran/eod2/assets/11193250/c95043e2-8727-472f-b2f1-fc5fb96e1bb3)

Check this URL. 
https://finlib.in/alphabets-in-the-stock-name/

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Ah! I didn't notice it. This makes it easier. But i will still maintain a separate repo for this until the code is stable and runs without any significant issues. I can always merge the code back into this repo if required. The code changes are minimal.

But i will need time, perhaps by month end i can start work on this. I will create a blank repo `eod2-sme` for now so we can move the discussion there.

Let me know your thoughts

**Comment by cotton1234** [comment]
Sure Benny, its fine.

**Comment by BennyThadikaran** [comment]
I assume you will need some historical data. I checked as of Dec 2015 there are just 4 stocks in this category. 
![Screenshot from 2023-08-09 13-52-34](https://github.com/BennyThadikaran/eod2/assets/19973418/f196e140-729e-4af4-a460-fa4d08abfb77)

So i guess 5 years historical data should be a good start?

Do these SME stocks go under ASM. Do they have their own sub categories like BE or BZ?

Are these companies allowed to declare splits and bonus? 

Do these companies get upgraded to the equity platform as and when they fulfill market listing requirements?

Just asking so we can avoid headaches in the future :stuck_out_tongue:

**Comment by cotton1234** [comment]
Let me check on the same and get back to you.

**Comment by BennyThadikaran** [comment]
I have opened a new issue https://github.com/BennyThadikaran/eod2-sme/issues/1 in eod2-sme. We can continue the discussion there. You can close this issue.
