### ISSUE TITLE
Data Update Error

### ISSUE THREAD

**Issue by rohit1409** [BennyThadikaran/eod2#59]
Hi Benny,

Firstly, this is amazing !, I have never seen something prepared so neatly. Kudos !

I tried this few days back and it ran well, however today I tried updating the data and encountered below error, couldn't figure out what's missing as internet connection is running well. I can download other stuff manually. Can you please suggest.

D:\eod2-main\src>init.py
Downloading Files
Download error. Try again later: ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(271 bytes read, 138 more expected)', IncompleteRead(271 bytes read, 138 more expected)))

**Comment by BennyThadikaran** [comment]
@rohit1409 
This error is because NSE has not updated a report - Full Bhavcopy and Security Deliverable data (sec_bhavdata_full_26102023.csv). [See NSE daily reports](https://www.nseindia.com/all-reports)

NSE sometimes delays its reports by a few hours. EOD2 will work just fine once the report becomes available. I encountered this error yesterday. At the time of this reply the report is still not updated. I would just retry on Monday after 7pm.

**Comment by rohit1409** [comment]
Thanks Benny, appreciate your prompt reply, happy coding :) !

**Comment by BennyThadikaran** [comment]
The error itself is quite ugly. :smiley_cat: Does not leave a good impression for new users.

When a report is unavailable, NSE server sends a HTML/text response and ends the connection. Since we are downloading in parts/chunks, after the first chunk is received, the connection is closed resulting in this error.

Thanks for reporting this. I'll try and catch this error early, so next time a more friendly message is displayed.

**Comment by rohit1409** [comment]
Most welcome... and I agree.. especially if someone not accustomed to NSE ways of working :)

**Comment by BennyThadikaran** [comment]
I don't think the delivery report for friday is coming. Still I will wait till evening. If today's report is available, friday delivery values will have to be set to 0 to continue.

I will put a mechanism is place so no manual intervention is required in future.

**Comment by BennyThadikaran** [comment]
@rohit1409 

NSE has updated its Friday report. You can go ahead and sync EOD2.
 
The error has been corrected by checking the content-type of the response. If its a text/html we raise a runtime error with a friendly message.
![error](https://github.com/BennyThadikaran/eod2/assets/19973418/2cb342b5-7212-4c14-b12f-136e68685b1d)

I made this change in [NseIndiaApi](https://github.com/BennyThadikaran/NseIndiaApi) with this [commit](https://github.com/BennyThadikaran/NseIndiaApi/commit/8d704c29861a66ef927bd1387b3a6fb025abcf04). EOD2 will start using this package for all NSE related functions.

As for the mechanism to prevent this breakdown entirely:
1. If delivery report if not available, create a entry for the day with NaN values. (Using 0 will cause averages to be skewed)
2. Create a log file with the date for which delivery file was not available.
3. On every sync, check for this log file. If it exists, retry downloading the delivery file for that date. 
4. Once download was successful, update the delivery info and delete the log file.
5. If file not available after 2 days on sync delete the log file.

This is just my initial thought. Since there is no urgency anymore, i will take a few days to roll this update. You can leave this issue open for the time being.

**Comment by rohit1409** [comment]
Hi Benny, Steps sounds fine, just a recommendation on your fifth point to have 5 working days instead of 2, why because normally eod/positional trading is analyzed weekly, and like in current example, by next friday if records are retrieved then analysis remain strong, else can be left blank.

**Comment by rohit1409** [comment]
And yes, please take your time, will look forward to the updates in coming days.

**Comment by BennyThadikaran** [comment]
Thanks for that tip. Will incorporate it
